_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.18.5
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
architecture:
    value: SIAMESE QUANTUM NETORK
dataset:
    value: Tyskdata
epochs:
    value: 10
learning_rate:
    value: 0.01
